baseURL = "/"
languageCode = "en"
title = "Jonathan Sanderson"

[Author]  
  name = "Jonathan Sanderson"

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
  title = "Jonathan Sanderson | Development & Design"
  description = "Text about my cool site"
  images = []