baseURL = "/"
languageCode = "en"
title = "Jonathan Sanderson"

[Author]  
  name = "Jonathan Sanderson"
  tagline = "Development & Design"
  about = "I help business owners unleash their earning potential.  I design and build custom digital assets to fullfill a vision. I embrace new technology. I teach new new developers and lead them to discover their potential"
  button1 = "Click here to send me a message"
  button2 = "Click here to see how I can help"

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
  title = "Jonathan Sanderson | Development & Design"
  description = "Text about my cool site"
  images = []